services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: event-counter-backend
    container_name: event-counter-backend
    env_file:
      - .env
    environment:
      - MONGODB_URI=MONGODB_URI
      - JWT_KEY=JWT_KEY
      - USER_SERVICE_URL=http://localhost:3000
      - STRIPE_SECRET_KEY=sk_live_STRIPE_SECRET_KEY
      - STRIPE_TEST_KEY=sk_test_STRIPE_TEST_KEY
      - WEBHOOK_LOCAL_SECRET=whsec_WEBHOOK_LOCAL_SECRET
      - GMAIL_USER=GMAIL_USER@gmail.com
      - GMAIL_PASS=GMAIL_PASS
      - FIREBASE_STORAGE_BUCKET=FIREBASE_STORAGE_BUCKET
    ports:
      - "8001:8001"
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: event-counter-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: "MONGO_INITDB_ROOT_USERNAME"
      MONGO_INITDB_ROOT_PASSWORD: "MONGO_INITDB_ROOT_PASSWORD"
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  node_modules:
  mongodb_data:
